#!/bin/bash
#BSUB -P malaria-dk
#BSUB -n 1
#BSUB -q normal
#BSUB -e /nfs/users/nfs_t/tn6/gitrepo/pf_swga_cnv/logs/depth_of_cov_swga_interval.chr5.lsf.%J.%I.e.log
#BSUB -o /nfs/users/nfs_t/tn6/gitrepo/pf_swga_cnv/logs/depth_of_cov_swga_interval.chr5.lsf.%J.%I.o.log
#BSUB -J depth_of_cov_swga_interval.chr5[1-160]
#BSUB -M 12288
#BSUB -R "select[mem>12288] rusage[mem=12288]"

source $HOME/vrpipe_prod_env.sh
set -e
set -x


OUTPUT_DIR=/lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv/output/depth_of_cov




# vrpipe-fileinfo --setup pf_swga_plex_indel_realign_bqsr --metadata sample,library,lane --step "gatk_print_reads_gatk3_v2|recalibrated_bam_files" > /lustre/scratch118/malaria/team112/pipelines/setups/pf_swga/resource/pf_swga_plex_indel_realign_bqsr.output.fofn
# vrpipe-fileinfo --setup pf_swga_plex_indel_realign_bqsr_fix_miss_mate --metadata sample,library,lane --step "gatk_print_reads_gatk3_v2|recalibrated_bam_files" | tail -n +2 >> /lustre/scratch118/malaria/team112/pipelines/setups/pf_swga/resource/pf_swga_plex_indel_realign_bqsr.output.fofn

# vrpipe-fileinfo --setup pf_swga_cnv_3D7_indel_realign_bqsr --metadata sample,library,lane --step "gatk_print_reads_gatk3_v2|recalibrated_bam_files" > /lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv_3D7/resource/pf_swga_cnv_3D7_indel_realign_bqsr.output.fofn
# vrpipe-fileinfo --setup pf_swga_cnv_wgs_indel_realign_bqsr --metadata sample,library,lane --step "gatk_print_reads_gatk3_v2|recalibrated_bam_files" > /lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv_wgs/resource/pf_swga_cnv_wgs_indel_realign_bqsr.output.fofn

INTERVAL_LIST=/lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv/output/primer_bind_sites/swga_p10_primer.3D7_v3_targets.chr5.bed
REFERENCE_FASTA=/lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv/resource/3D7/3D7_V3.fasta


PF_SWGA_FOFN=/lustre/scratch118/malaria/team112/pipelines/setups/pf_swga/resource/pf_swga_plex_indel_realign_bqsr.output.fofn

FOFN=$PF_SWGA_FOFN
FOFN_IDX=$(( $LSB_JOBINDEX + 1 ))  # Offset because there is a header line in the fofn


BAM=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 1  )
SAMPLE=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 2  )
LIBRARY=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 3  )
LANE=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 4  )

echo "Using LSB_JOBINDEX=${LSB_JOBINDEX} which translates to FOFN_IDX=$FOFN_IDX in FOFN=$FOFN, where FOFN_IDX is 1-based and header is FOFN_IDX=1"
echo SAMPLE=$SAMPLE  LIBRARY=$LIBRARY LANE=$LANE BAM=$BAM
echo "Using LSB_JOBINDEX=${LSB_JOBINDEX} which translates to FOFN_IDX=$FOFN_IDX in FOFN=$FOFN, where FOFN_IDX is 1-based and header is FOFN_IDX=1"
echo SAMPLE=$SAMPLE

# touch $OUTPUT_DIR/test_lsf.$LSB_JOBINDEX.$FOFN_IDX.$SAMPLE.$LIBRARY.$LANE.txt

java -jar /software/vertres/bin-external/GenomeAnalysisTK-3.6/GenomeAnalysisTK.jar \
         -T DepthOfCoverage \
         -R $REFERENCE_FASTA \
         -o $OUTPUT_DIR/$SAMPLE.$LIBRARY.$LANE.chr5 \
         -I $BAM \
         -L $INTERVAL_LIST \
          --countType COUNT_FRAGMENTS         \
         --includeRefNSites \
         --minBaseQuality 0 \
         --minMappingQuality 20 \
         --start 1 --stop 7000 --nBins 6999 \
         --omitDepthOutputAtEachBase \
         --omitLocusTable \
         --omitPerSampleStats
