#!/bin/bash
#BSUB -P malaria-dk
#BSUB -n 1
#BSUB -q normal
#BSUB -e /nfs/users/nfs_t/tn6/gitrepo/NoPCR/logs/picard_genotypeconcordance.lsf.%J.%I.e.log
#BSUB -o /nfs/users/nfs_t/tn6/gitrepo/NoPCR/logs/picard_genotypeconcordance.lsf.%J.%I.o.log
#BSUB -J picard_genotypeconcordance[1-86]  # parallelize each nopcr, pf61 bam
#BSUB -M 12288
#BSUB -R "select[mem>12288] rusage[mem=12288]"

source $HOME/vrpipe_prod_env.sh
set -e
set -x


OUTPUT_DIR=/lustre/scratch118/malaria/team112/pipelines/setups/nopcr/output/picard_genotypeconcordance
RESOURCE_DIR=/lustre/scratch118/malaria/team112/pipelines/setups/nopcr/resources



# vrpipe-fileinfo --setup pf_swga_plex_indel_realign_bqsr --metadata sample,library,lane --step "gatk_print_reads_gatk3_v2|recalibrated_bam_files" > /lustre/scratch118/malaria/team112/pipelines/setups/pf_swga/resource/pf_swga_plex_indel_realign_bqsr.output.fofn
# vrpipe-fileinfo --setup pf_swga_cnv_3D7_indel_realign_bqsr --metadata sample,library,lane --step "gatk_print_reads_gatk3_v2|recalibrated_bam_files" > /lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv_3D7/resource/pf_swga_cnv_3D7_indel_realign_bqsr.output.fofn
# vrpipe-fileinfo --setup pf_swga_cnv_wgs_indel_realign_bqsr --metadata sample,library,lane --step "gatk_print_reads_gatk3_v2|recalibrated_bam_files" > /lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv_wgs/resource/pf_swga_cnv_wgs_indel_realign_bqsr.output.fofn

# We already know that there are only 86 PF61 samples but 96 NoPCR samples,
# so we only use the subset of samples listed in PF61 fofn in our LSB_JOBINDEX.
REFERENCE_FASTA=/lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv/resource/3D7/3D7_V3.fasta


PF_SWGA_FOFN=/lustre/scratch118/malaria/team112/pipelines/setups/pf_swga/resource/pf_swga_plex_indel_realign_bqsr.output.fofn
PF_3D7_FOFN=/lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv_3D7/resource/pf_swga_cnv_3D7_indel_realign_bqsr.output.fofn
PF_WGS_FOFN=/lustre/scratch118/malaria/team112/personal/tn6/pf_swga_cnv_wgs/resource/pf_swga_cnv_wgs_indel_realign_bqsr.output.fofn


LEN_PF_SWGA_FOFN=$(( $(wc -l $PF_SWGA_FOFN | cut -f 1 -d " ") - 1))  # Remove the filename from wc output before arithmetic.  Remove the header line from the line count.
LEN_PF_3D7_FOFN=$(( $(wc -l $PF_SWGA_FOFN | cut -f 1 -d " ") - 1))  # Remove the filename from wc output before arithmetic.  Remove the header line from the line count.
LEN_PF_WGS_FOFN=$(( $(wc -l $PF_SWGA_FOFN | cut -f 1 -d " ") - 1))  # Remove the filename from wc output before arithmetic.  Remove the header line from the line count.


FOFN=$NOPCR_FOFN
FOFN_IDX=$(( $LSB_JOBINDEX + 1 ))  # Offset because there is a header line in the fofn
if (("$LSB_JOBINDEX" > "$LEN_NOPCR_FOFN"))
then
  FOFN=$PF61_FOFN
  FOFN_IDX=$(( $LSB_JOBINDEX - $LEN_NOPCR_FOFN + 1 ))
fi

BAM=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 1  )
SAMPLE=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 2  )
LIBRARY=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 3  )
LANE=$( sed -n "${FOFN_IDX}p"  $FOFN | cut -f 4  )

echo "Using LSB_JOBINDEX=${LSB_JOBINDEX} which translates to FOFN_IDX=$FOFN_IDX in FOFN=$FOFN, where FOFN_IDX is 1-based and header is FOFN_IDX=1"
echo SAMPLE=$SAMPLE  LIBRARY=$LIBRARY LANE=$LANE BAM=$BAM
echo "Using LSB_JOBINDEX=${LSB_JOBINDEX} which translates to FOFN_IDX=$FOFN_IDX in FOFN=$FOFN, where FOFN_IDX is 1-based and header is FOFN_IDX=1"
echo SAMPLE=$SAMPLE

# touch $OUTPUT_DIR/test_lsf.$LSB_JOBINDEX.$FOFN_IDX.$SAMPLE.$LIBRARY.$LANE.txt

java -jar /software/vertres/bin-external/GenomeAnalysisTK-3.6/GenomeAnalysisTK.jar \
         -T DepthOfCoverage \
         -R $REFERENCE_FASTA \
         -o file_name_base \
         -I $SAMPLE_BAM \
         # count all reads from same fragments even if mismatch base
         --countType COUNT_FRAGMENTS \
         --includeRefNSites \
         --minBaseQuality 0 \
         --minMappingQuality 20 \
         --start 1 --stop 7000 --nBins 7001 \


         [-geneList refSeq.sorted.txt] \
         [-pt readgroup] \
         [-ct 4 -ct 6 -ct 10] \
         [-L my_capture_genes.interval_list] \


         java -Xmx3072m -jar ./Sting/dist/GenomeAnalysisTK.jar \
         -T DepthOfCoverage -I $SAMPLE_BAM -L EXOME.interval_list \
         -R ./human_g1k_v37.fasta \
         -dt BY_SAMPLE  # We do not want to downsample!

         -dcov 5000 -l INFO --omitDepthOutputAtEachBase --omitLocusTable \
         --minBaseQuality 0 --minMappingQuality 20 --start 1 --stop 5000 --nBins 200 \
         --includeRefNSites \
         --countType COUNT_FRAGMENTS \
         -o group1.DATA
